In [4]:
 pip install numpy

Requirement already satisfied: numpy in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (2.0.2)Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the 'c:\Users\HP\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [5]:
pip install pandas

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (2.3.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the 'c:\Users\HP\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [6]:
pip install seaborn

Requirement already satisfied: seaborn in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (0.13.2)
Requirement already satisfied: pandas>=1.2 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from seaborn) (2.3.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from seaborn) (3.9.4)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from seaborn) (2.0.2)
Requirement already satisfied: pillow>=8 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.7)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.59.0)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (6.5.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.0)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: zipp>=3.1.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from importlib-resources>=3.2.0->matplotlib!=3.6.1,>=3.4->seaborn) (3.23.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the 'c:\Users\HP\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [7]:
pip install matplotib

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement matplotib (from versions: none)
ERROR: No matching distribution found for matplotib
WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the 'c:\Users\HP\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [8]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: scikit-learn in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (1.6.1)
Requirement already satisfied: scipy>=1.6.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: numpy>=1.19.5 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from scikit-learn) (1.5.1)

WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the 'c:\Users\HP\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [10]:
df=pd.read_csv("J:\Social_Network_Ads.csv")
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [11]:
df.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [12]:
df.shape

(400, 5)

In [13]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [14]:
df.corr

<bound method DataFrame.corr of       User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]>

In [15]:
le=LabelEncoder()
df["Gender"]=le.fit_transform(df["Gender"])# we can replace gender values with 0 and 1

In [16]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

In [17]:
df["gender"]=None  # To create a new column for a dataset social media

In [18]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased gender
0  15624510       1   19            19000          0   None
1  15810944       1   35            20000          0   None
2  15668575       0   26            43000          0   None
3  15603246       0   27            57000          0   None
4  15804002       1   19            76000          0   None

In [19]:
df["gender"]=np.random.choice(["M","F"],size=len(df)) # It is used to fill  the null values with male and female

In [20]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased gender
0  15624510       1   19            19000          0      F
1  15810944       1   35            20000          0      M
2  15668575       0   26            43000          0      F
3  15603246       0   27            57000          0      F
4  15804002       1   19            76000          0      M

In [21]:
le=LabelEncoder()
df["gender"]=le.fit_transform(df["gender"]) # If we place gender as Gender it shows none values in both Gender and gender(it is used to get numeric values)

In [22]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased  gender
0  15624510       1   19            19000          0       0
1  15810944       1   35            20000          0       1
2  15668575       0   26            43000          0       0
3  15603246       0   27            57000          0       0
4  15804002       1   19            76000          0       1

In [23]:
x=df.drop(['Purchased','User ID','Gender'],axis=1)
y=df['Purchased']

In [24]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
ss=StandardScaler()# The Standard scalar has not fixed values-->It applicable to normal distribution convert to standerization 
mm=MinMaxScaler() # The minmax scalar has fixed values-->It applyied to left and right skewed
df["EstimatedSalary"]=ss.fit_transform(df[["EstimatedSalary"]])
df["EstimatedSalary"]=mm.fit_transform(df[["EstimatedSalary"]])

In [25]:
ss.fit(df)

StandardScaler()

In [26]:
ss.transform(df)

array([[-0.93657932,  1.02020406, -1.78179743, -1.49004624, -0.74593581,
        -0.95118973],
       [ 1.66838653,  1.02020406, -0.25358736, -1.46068138, -0.74593581,
         1.05131497],
       [-0.32087714, -0.98019606, -1.11320552, -0.78528968, -0.74593581,
        -0.95118973],
       ...,
       [-0.52039175, -0.98019606,  1.17910958, -1.46068138,  1.34059793,
        -0.95118973],
       [ 0.88695546,  1.02020406, -0.15807423, -1.07893824, -0.74593581,
        -0.95118973],
       [-1.36231017, -0.98019606,  1.08359645, -0.99084367,  1.34059793,
        -0.95118973]])

In [27]:
mm.fit(df)

MinMaxScaler()

In [28]:
mm.transform(df)

array([[0.23263608, 1.        , 0.02380952, 0.02962963, 0.        ,
        0.        ],
       [0.98273164, 1.        , 0.4047619 , 0.03703704, 0.        ,
        1.        ],
       [0.40992649, 0.        , 0.19047619, 0.20740741, 0.        ,
        0.        ],
       ...,
       [0.35247659, 0.        , 0.76190476, 0.03703704, 1.        ,
        0.        ],
       [0.75771987, 1.        , 0.42857143, 0.13333333, 0.        ,
        0.        ],
       [0.1100476 , 0.        , 0.73809524, 0.15555556, 1.        ,
        0.        ]])