In [18]:
%pip install numpy

Requirement already satisfied: numpy in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (2.0.2)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the 'c:\Users\HP\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [19]:
%pip install seaborn

Requirement already satisfied: seaborn in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (0.13.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from seaborn) (3.9.4)
Requirement already satisfied: pandas>=1.2 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from seaborn) (2.3.1)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from seaborn) (2.0.2)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.0)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (6.5.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.59.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: pillow>=8 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.7)
Requirement already satisfied: zipp>=3.1.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from importlib-resources>=3.2.0->matplotlib!=3.6.1,>=3.4->seaborn) (3.23.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the 'c:\Users\HP\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [20]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the 'c:\Users\HP\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [21]:
%pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (3.9.4)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: numpy>=1.23 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib) (2.0.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib) (6.5.2)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from matplotlib) (4.59.0)
Requirement already satisfied: zipp>=3.1.0 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from importlib-resources>=3.2.0->matplotlib) (3.23.0)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.4; however, version 25.2 is available.
You should consider upgrading via the 'c:\Users\HP\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

In [22]:
import numpy as np
import pandas as pd
import seaborn as sbs
import matplotlib.pyplot as plt

In [23]:
df=pd.read_csv("J:\health care diabetes.csv")
df.head(7)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,NaN,NaN
1,1,85,66,29,0,26.6,NaN,31.0,0.0
2,8,183,64,0,0,23.3,0.672,32.0,0.0
3,1,89,66,23,94,28.1,0.167,21.0,0.0
4,0,137,40,35,168,43.1,NaN,NaN,0.0
5,5,116,74,0,0,25.6,0.201,34.0,0.0
6,3,78,50,32,88,31.0,0.248,26.0,1.0

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  766 non-null    float64
 7   Age                       766 non-null    float64
 8   Outcome                   767 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 54.1 KB

In [25]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,766.000000,766.000000,767.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.469663,33.224543,0.345502
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.325162,11.759428,0.475842
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243250,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.625500,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [26]:
df.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.026309,0.544630,0.221220
Glucose,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.136047,0.262409,0.459962
BloodPressure,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.053083,0.240011,0.069841
SkinThickness,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.181425,-0.116490,0.074432
Insulin,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.183037,-0.041248,0.132022
BMI,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.133104,0.035634,0.292371
DiabetesPedigreeFunction,-0.026309,0.136047,0.053083,0.181425,0.183037,0.133104,1.000000,0.033085,0.165120
Age,0.544630,0.262409,0.240011,-0.116490,-0.041248,0.035634,0.033085,1.000000,0.236922
Outcome,0.221220,0.459962,0.069841,0.074432,0.132022,0.292371,0.165120,0.236922,1.000000

In [27]:
dt=df["Pregnancies"].corr(df["Outcome"])
print(dt)

0.2212199427732872

In [28]:
de=df["BloodPressure"].corr(df["Outcome"])
print(de)

0.06984124408093655

In [29]:
df.nunique()

Pregnancies                  17
Glucose                     136
BloodPressure                47
SkinThickness                51
Insulin                     186
BMI                         248
DiabetesPedigreeFunction    515
Age                          52
Outcome                       2
dtype: int64

In [30]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    2
Age                         2
Outcome                     1
dtype: int64

In [31]:
dg={
    "A":[1,2,3,None],
    "B":[3,5,None],
    "C":[6,7,8,None]
}
da=pd.DataFrame(dg)
print(da)

ValueError: All arrays must be of the same length

In [ ]:
da.head()

NameError: name 'da' is not defined